var charArray = [
  "Reimu Hakurei",
  "Marisa Kirisame",
  "Rumia",
  "Daiyousei",
  "Cirno",
  "Hong Meiling",
  "Koakuma",
  "Patchouli Knowledge",
  "Sakuya Izayoi",
  "Remilia Scarlet",
  "Flandre Scarlet",
  "Letty Whiterock",
  "Chen",
  "Alice Margatroid",
  "Lily White",
  "Lunasa Prismriver",
  "Merlin Prismriver",
  "Lyrica Prismriver",
  "Youmu Konpaku",
  "Yuyuko Saigyouji",
  "Ran Yakumo",
  "Yukari Yakumo",
  "Suika Ibuki",
  "Wriggle Nightbug",
  "Mystia Lorelei",
  "Keine Kamishirasawa",
  "Tewi Inaba",
  "Reisen Udongein Inaba",
  "Eirin Yagokoro",
  "Kaguya Houraisan",
  "Fujiwara no Mokou",
  "Aya Shameimaru",
  "Medicine Melancholy",
  "Yuuka Kazami",
  "Komachi Onozuka",
  "Eiki Shiki, Yamaxanadu",
  "Shizuha Aki",
  "Minoriko Aki",
  "Hina Kagiyama",
  "Nitori Kawashiro",
  "Momiji Inubashiri",
  "Sanae Kochiya",
  "Kanako Yasaka",
  "Suwako Moriya",
  "Iku Nagae",
  "Tenshi Hinanawi",
  "Kisume",
  "Yamame Kurodani",
  "Parsee Mizuhashi",
  "Yuugi Hoshiguma",
  "Satori Komeiji",
  "Rin Kaenbyou (Orin)",
  "Utsuho Reiuji (Okuu)",
  "Koishi Komeiji",
  "Nazrin",
  "Kogasa Tatara",
  "Ichirin Kumoi",
  "Minamitsu Murasa",
  "Shou Toramaru",
  "Byakuren Hijiri",
  "Nue Houjuu",
  "Hatate Himekaidou",
  "Sunny Milk",
  "Luna Child",
  "Star Sapphire",
  "Kyouko Kasodani",
  "Yoshika Miyako",
  "Seiga Kaku",
  "Soga no Tojiko",
  "Mononobe no Futo",
  "Toyosatomimi no Miko",
  "Mamizou Futatsuiwa",
  "Hata no Kokoro",
  "Wakasagihime",
  "Sekibanki",
  "Kagerou Imaizumi",
  "Benben Tsukumo",
  "Yatsuhashi Tsukumo",
  "Seija Kijin",
  "Shinmyoumaru Sukuna",
  "Raiko Horikawa",
  "Sumireko Usami",
  "Seiran",
  "Ringo",
  "Doremy Sweet",
  "Sagume Kishin",
  "Clownpiece",
  "Junko",
  "Hecatia Lapislazuli",
  "Hieda no Akyuu",
  "Tokiko",
  "Reisen (Manga)",
  "Watatsuki no Toyohime",
  "Watatsuki no Yorihime",
  "Maribel Hearn",
  "Renko Usami",
  "Kasen Ibaraki",
  "Kosuzu Motoori",
  "Reimu Hakurei (PC-98)",
  "Shingyoku (Female)",
  "Mima",
  "Elis",
  "Kikuri",
  "Sariel",
  "Konngara",
  "Rika",
  "Meira",
  "Marisa Kirisame (PC-98)",
  "Ellen",
  "Kotohime",
  "Kana Anaberal",
  "Rikako Asakura",
  "Chiyuri Kitashirakawa",
  "Yumemi Okazaki",
  "Ruukoto",
  "Orange",
  "Kurumi",
  "Elly",
  "Yuuka (PC-98)",
  "Mugetsu",
  "Gengetsu",
  "Sara",
  "Louise",
  "Alice (PC-98)",
  "Yuki",
  "Mai",
  "Yumeko",
  "Shinki",
  "Mimi-chan",
  "Unzan",
  "Genji",
  "Shingyoku (Male)",
  "YuugenMagan",
  "Evil Eye Sigma",
  "Great Catfish",
  "Rinnosuke Morichika",
  "Fortune Teller",
  "Hisoutensoku"
]

module.exports = {
	desc: "Gives a random Touhou character.\nUSAGE: -rand2hu",
	lvl: "author",
	func (msg, cmd, bot) {
		msg.channel.send(charArray[Math.floor(Math.random() * charArray.length)]);
	}
}